import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";
import Footer from "@/src/components/footer";
import Image from "next/image";
import Link from "next/link";
import zapformsLogo from "../assets/zapformslogo.png"; // Static import
import { standardMargin } from "../src/utils/index";
import { SnackbarProvider } from "@/src/providers/snackbarProvide";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const Routes=[
    {label:"Create form" , href:"/create"},
    {label:"Forms" , href:"/forms"},
    ]
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <HeroUIProvider>
          <div className={``}>
            <div
              style={{ boxShadow: "rgba(100, 100, 111, 0.2) 0px 7px 29px 0px" }}
              className=" flex flex-row justify-between h-16 w-full px-6"
            >
              <div  className="flex flex-row justify-center cursor-poiter items-center overflow-hidden">
              <Link href={"/"}>
                <Image
                  alt="zapformslogo"
                  src={zapformsLogo}
                  width={100}
                  height={100}
                />
                </Link>
              </div>
              <div className="flex flex-row items-center">
                <ul className="flex">
                  {
                    Routes.map(({label , href})=>{
                      return <li key={label} className="m-3 font-semibold">
                      <Link href={href}>{label}</Link>
                    </li>
                    })
                  }
                </ul>
              </div>
            </div>
            <div className={`min-h-[100vh]`}>
              <SnackbarProvider>
              {children}
              </SnackbarProvider>
           </div>
          </div>
        </HeroUIProvider>

        <Footer />
      </body>
    </html>
  );
}
